### ISSUE TITLE
Not support Ubuntu?

### ISSUE THREAD

**Issue by zhanga5** [hetzneronline/go-lvm#2]
As the dbus message with prefix com.redhat.lvmdbus1, does it mean only support Redhat platform? I just did a quick testing on Ubuntu 14.04.5, always got nothing when query managed objects. Did I miss anything?

**Comment by tonobo** [comment]
`com.redhat` just declares the vendor part. Please ensure your running lvmdbusd. Probaply this is unavailable in trusty. I've launched the testes with debian sid, but bionic seems to be also support lvmdbusd.

**Comment by zhanga5** [comment]
I see. Yes, quick check indicated only latest Bionic included this service.
Anyway, thanks for the info!
